const actionTypes = {
  POSTS_REQUEST: 'POSTS_REQUEST',
  POSTS_REQUEST_SUCCESS: 'POSTS_REQUEST_SUCCESS',
  POSTS_REQUEST_FAILURE: 'POSTS_REQUEST_FAILURE',
  POSTS_REQUEST_CANCEL: 'POSTS_REQUEST_CANCEL',
  POST_CREATE_REQUEST: 'POST_CREATE_REQUEST',
  POST_CREATE_REQUEST_SUCCESS: 'POST_CREATE_REQUEST_SUCCESS',
  POST_CREATE_REQUEST_FAILURE: 'POST_CREATE_REQUEST_FAILURE',
  POSTS_USER_REQUEST: 'POSTS_USER_REQUEST',
  POSTS_USER_REQUEST_SUCCESS: 'POSTS_USER_REQUEST_SUCCESS',
  POSTS_USER_REQUEST_FAILURE: 'POSTS_USER_REQUEST_FAILURE',
  POST_EDIT_REQUEST: 'POST_EDIT_REQUEST',
  POST_EDIT_REQUEST_SUCCESS: 'POST_EDIT_REQUEST_SUCCESS',
  POST_EDIT_REQUEST_FAILURE: 'POST_EDIT_REQUEST_FAILURE',
  POSTS_POP_UP_CLEAR: 'POSTS_POP_UP_CLEAR',
  POST_DELETE_REQUEST: 'POST_DELETE_REQUEST',
  POST_DELETE_REQUEST_SUCCESS: 'POST_DELETE_REQUEST_SUCCESS',
  POST_DELETE_REQUEST_FAILURE: 'POST_DELETE_REQUEST_FAILURE'
}

export default actionTypes;