const actionTypes = {
  NOTIFICATIONS_REQUEST: 'NOTIFICATIONS_REQUEST',
  NOTIFICATIONS_REQUEST_SUCCESS: 'NOTIFICATIONS_REQUEST_SUCCESS',
  NOTIFICATIONS_REQUEST_FAILURE: 'NOTIFICATIONS_REQUEST_FAILURE',
  NOTIFICATIONS_REQUEST_CANCEL: 'NOTIFICATIONS_REQUEST_CANCEL'
}

export default actionTypes;