const actionTypes = {
  SIGN_IN_REQUEST: 'SIGN_IN_REQUEST',
  SIGN_IN_REQUEST_SUCCESS: 'SIGN_IN_REQUEST_SUCCESS',
  SIGN_IN_REQUEST_FAILURE: 'SIGN_IN_REQUEST_FAILURE',
  SIGN_UP_REQUEST: 'SIGN_UP_REQUEST',
  SIGN_UP_REQUEST_SUCCESS: 'SIGN_UP_REQUEST_SUCCESS',
  SIGN_UP_REQUEST_FAILURE: 'SIGN_UP_REQUEST_FAILURE',
  SIGN_OUT: 'SIGN_OUT',
  AUTH_POP_UP_CLEAR: 'AUTH_POP_UP_CLEAR',
}

export default actionTypes